version: "3.7"

services:
  # 🔹 Serviço do Prometheus (Coletor de Métricas)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - observability

  # 🔹 Serviço do Loki (Armazenamento de Logs)
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - observability

  # 🔹 Serviço do OpenTelemetry Collector (Traces, Logs e Métricas)
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: always
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    volumes:
      - ./opentelemetry/config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    networks:
      - observability

  # 🔹 Serviço do Grafana (Visualização de Métricas e Logs)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/config/dashboards.json:/etc/grafana/provisioning/dashboards/dashboards.json
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - observability

  # 🔹 Serviço do Portainer (Gerenciamento de Containers)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/config:/data
    networks:
      - observability

  # 🔹 Serviço do SWAG (Let's Encrypt via Cloudflare)
  letsencrypt:
    container_name: letsencrypt
    image: linuxserver/swag
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - URL=meudominio.com.br # Substitua pelo domínio real
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=email@meudominio.com.br # Substitua pelo seu e-mail real
      - DHLEVEL=4096
    volumes:
      - ./letsencrypt:/config
    networks:
      - observability

  # 🔹 Serviço do Nginx (Proxy Reverso)
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/sites-available:/etc/nginx/sites-available
      - ./nginx/conf.d/sites-enabled:/etc/nginx/sites-enabled
      - ./letsencrypt:/etc/letsencrypt # Monta os certificados SSL gerados pelo SWAG
    depends_on:
      - letsencrypt
      - grafana
      - prometheus
    networks:
      - observability

networks:
  observability:
    driver: bridge
