global:
  scrape_interval: 15s
  scrape_timeout: 10s # Ajuste o tempo de timeout se necessário

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "otel-collector"
    static_configs:
      - targets: ["localhost:4317"]
