global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Prometheus monitorando a si mesmo

  - job_name: "application"
    static_configs:
      - targets: ["application:8000"] # Nome do serviço da aplicação no Docker Compose

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:4317"] # Nome do serviço otel-collector
