global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus.sallesarchcloud.com.br:9090"]

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector.sallesarchcloud.com.br:4317"]
